on: push
name: sguav.github.io blog deploy

permissions:
  contents: write
  
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}
